<a href="https://colab.research.google.com/github/Karsuman4298/Machine_learning/blob/main/Naive_Bayes_VS_Logistic_Reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import classification_report,confusion_matrix
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('naive_bayes_10000_dataset.csv')
df

      gender  cgpa  attendance  ... backlogs  extracurricular placed
0       Male  7.19       79.99  ...        2               No      0
1     Female  7.54       89.87  ...        0               No      1
2       Male  9.17       82.51  ...        0              Yes      0
3       Male  6.96       63.33  ...        1               No      0
4       Male  9.24       67.42  ...        1               No      1
...      ...   ...         ...  ...      ...              ...    ...
9995  Female  8.30       73.10  ...        1               No      1
9996    Male  6.26       89.08  ...        1              Yes      1
9997  Female  5.72       96.93  ...        1               No      1
9998  Female  8.44       85.49  ...        2              Yes      0
9999    Male  6.58       98.07  ...        3              Yes      0

[10000 rows x 11 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           10000 non-null  object
 1   cgpa             10000 non-null  float64
 2   attendance       10000 non-null  float64
 3   internship       10000 non-null  object
 4   projects         10000 non-null  int64
 5   communication    10000 non-null  object
 6   aptitude_score   10000 non-null  int64
 7   coding_score     10000 non-null  int64
 8   backlogs         10000 non-null  int64
 9   extracurricular  10000 non-null  object
 10  placed           10000 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 859.5+ KB

In [5]:
df.isnull().sum()

gender             0
cgpa               0
attendance         0
internship         0
projects           0
communication      0
aptitude_score     0
coding_score       0
backlogs           0
extracurricular    0
placed             0
dtype: int64

In [6]:
df.describe()

               cgpa    attendance  ...      backlogs        placed
count  10000.000000  10000.000000  ...  10000.000000  10000.000000
mean       7.634626     80.329206  ...      1.483100      0.431300
std        1.239418     11.530375  ...      1.123317      0.495283
min        5.500000     60.000000  ...      0.000000      0.000000
25%        6.560000     70.430000  ...      0.000000      0.000000
50%        7.610000     80.515000  ...      1.000000      0.000000
75%        8.720000     90.132500  ...      2.000000      1.000000
max        9.800000    100.000000  ...      3.000000      1.000000

[8 rows x 7 columns]

In [ ]:
target_col=df.columns[-1]
X=df.drop(target_col,axis=1)
y=df[target_col]
le=LabelEncoder()
y=le.fit_transform(y)
X=pd.get_dummies(X)

In [7]:
categorical_cols = ['gender', 'internship', 'communication', 'extracurricular']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
display(df.head())